heat_template_version: 2015-04-30

description: Desarrollo del taller 1 app en la nube

parameters:

  public_network:
    type: string
    label: Public network with name or ID
    description: Public network with floating IP addresses
    default: ext-net-doctorado

resources:

  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: { get_param: public_network }
      
